enum GedString: String {
    // App
    case privacy = "privacy"
    case blockedUsers = "blocked_users"
    case blockedUser = "blocked_user"
    case noBlockedUser = "no_blocked_user"
    case profile = "profile"
    case account = "account"
    case accountInfos = "account_infos"
    case schoolLevel = "school_level"
    case editProfile = "edit_profile"
    case newProfilePicture = "new_profile_picture"
    case profilePictureUpdated = "profile_picture_updated"
    case member = "member"
    case userNotFound = "user_not_found"
    case deleteProfilePictureAlertMessage = "delete_profile_picture_alert_message"
    case deleteAccountText = "delete_account_text"
    case deleteAccount = "delete_account"
    case logoutAlertMessage = "logout_alert_message"
    case enterPassword = "enter_password"
    
    // App error
    case incorrectPasswordError = "incorrect_password_error"
    
    // Common
    case appName = "app_name"
    case next = "next"
    case back = "back"
    case cancel = "cancel"
    case ok = "ok"
    case delete = "delete"
    case edit = "edit"
    case save = "save"
    case now = "now"
    case finish = "finish"
    case resend = "resend"
    case loading = "loading"
    case send = "send"
    case minutesAgoShort = "minutes_ago_short"
    case hoursAgoShort = "hours_ago_short"
    case daysAgoShort = "days_ago_short"
    case weeksAgoShort = "weeks_ago_short"
    case today = "today"
    case yesterday = "yesterday"
    case home = "home"
    case sending = "sending"
    case report = "report"
    case block = "block"
    case unblock = "unblock"
    case blockUserAlertTitle = "block_user_alert_title"
    case blockUserAlertMessage = "block_user_alert_message"
    case unblockUserAlertMessage = "unblock_user_alert_message"
    
    // Common errors
    case mandatoryFieldError = "mandatory_field_error"
    case emptyInputsError = "empty_inputs_error"
    case timeOutError = "time_out_error"
    case noInternetConectionError = "no_internet_connection_error"
    case internalServerError = "internal_server_error"
    case unknownError = "unknown_error"
    case unknownNetworkError = "unknown_network_error"
    case userNotFoundError = "user_not_found_error"
    case cannotConnectToHostError = "cannot_connect_to_host_error"
    case tooManyRequestsError = "too_many_requests_error"
    case internetConnectionLostError = "internet_connection_lost_error"

    // Authentication
    case authenticationPageTitle = "authentication_page_title"
    case authenticationPageSubtitle = "authentication_page_subtitle"
    case firstName = "first_name"
    case lastName = "last_name"
    case email = "email"
    case password = "password"
    case login = "login"
    case logout = "logout"
    case register = "register"
    case registration = "registration"
    case notRegisterYet = "not_register_yet"
    case forgotPassword = "forgot_password"
    case forgotPasswordDescription = "forgot_password_description"
    case registrationStep = "registration_step"
    case selectSchoolLevel = "select_school_level"
    case level = "level"
    case enterNames = "enter_names"
    case enterEmailPassword = "enter_email_password"
    case forgotPasswordSuccess = "forgot_password_success"
    case agreeTermsPrivacyBeginningText = "agree_terms_privacy_beginning_text"
    case termsAndPrivacy = "terms_and_privacy"
    
    // Authentication errors
    case incorrectEmailFormatError = "incorrect_email_format_error"
    case passwordLengthError = "password_length_error"
    case incorrectCredentialsError = "incorrect_credentials_error"
    case userDisabledError = "user_disabled_error"
    case userNotExistError = "user_not_exist_error"
    case emailAlreadyAssociatedError = "email_already_associated_error"
    case legalNoticeError = "legal_notice_error"
    case userNotWhiteListedError = "user_not_white_listed_error"
    
    // News
    case news = "news"
    case announcement = "announcement"
    case recentAnnouncements = "recent_announcements"
    case newAnnouncement = "new_announcement"
    case editAnnouncement = "edit_announcement"
    case title = "title"
    case content = "content"
    case post = "post"
    case announcementCreated = "announcement_created"
    case noAnnouncement = "no_announcement"
    case deleteAnnouncementAlertMessage = "delete_announcement_alert_message"
    
    // Message
    case messages = "messages"
    case tapToChat = "tap_to_chat"
    case messagePlaceholder = "message_placeholder"
    case newConversation = "new_conversation"
    case noConversation = "no_conversation"
    case deleteConversationAlertTitle = "delete_conversation_alert_title"
    case deleteConversationAlertMessage = "delete_conversation_alert_message"
    case seen = "seen"
    case newMessages = "new_messages"
    case deleteMessageAlertContent = "delete_message_alert_content"
    case chatBlockedUserIndicatorText = "chat_blocked_user_indicator_text"
}
