enum StringResource: String {
    // App
    case privacy = "privacy"
    case blockedUsers = "blocked_users"
    case blockedUser = "blocked_user"
    case noBlockedUser = "no_blocked_user"
    case profile = "profile"
    case account = "account"
    case accountInfos = "account_infos"
    case schoolLevel = "school_level"
    case editProfile = "edit_profile"
    case newProfilePicture = "new_profile_picture"
    case profilePictureUpdated = "profile_picture_updated"
    case member = "member"
    case deleteProfilePictureAlertMessage = "delete_profile_picture_alert_message"
    case deleteAccountText = "delete_account_text"
    case deleteAccount = "delete_account"
    case logoutAlertMessage = "logout_alert_message"
    case enterPassword = "enter_password"
    case deletedUser = "deleted_user"
    
    // App error
    case incorrectPasswordError = "incorrect_password_error"
    
    // Common
    case appName = "app_name"
    case next = "next"
    case back = "back"
    case cancel = "cancel"
    case ok = "ok"
    case delete = "delete"
    case edit = "edit"
    case save = "save"
    case now = "now"
    case finish = "finish"
    case retry = "retry"
    case loading = "loading"
    case send = "send"
    case publish = "publish"
    case add = "add"
    case search = "search"
    case minutesAgoShort = "minutes_ago_short"
    case hoursAgoShort = "hours_ago_short"
    case daysAgoShort = "days_ago_short"
    case weeksAgoShort = "weeks_ago_short"
    case today = "today"
    case yesterday = "yesterday"
    case home = "home"
    case sending = "sending"
    case report = "report"
    case block = "block"
    case unblock = "unblock"
    case confirm = "confirm"
    case remove = "remove"
    case blockUserAlertTitle = "block_user_alert_title"
    case blockUserAlertMessage = "block_user_alert_message"
    case unblockUserAlertMessage = "unblock_user_alert_message"
    case noUser = "no_user"
    case noUsersFound = "no_users_found"
    case deletedUserFirstName = "deleted_user_first_name"
    case deletedUserLastName = "deleted_user_last_name"
    case mb = "mb"
    
    // Common errors
    case mandatoryFieldError = "mandatory_field_error"
    case emptyInputsError = "empty_inputs_error"
    case timedOutError = "timed_out_error"
    case noInternetConectionError = "no_internet_connection_error"
    case internalServerError = "internal_server_error"
    case unknownError = "unknown_error"
    case anyNetworkError = "any_network_error"
    case currentUserNotFoundError = "current_user_not_found_error"
    case cannotConnectToHostError = "cannot_connect_to_host_error"
    case tooManyRequestsError = "too_many_requests_error"
    case internetConnectionLostError = "internet_connection_lost_error"
    case disabledUserError = "disabled_user_error"
    case sendingError = "sending_error"
    case networkConnectionLostError = "network_connection_lost_error"
    case cannotFindHostError = "cannot_find_host_error"
    case numberFieldError = "number_field_error"
    case invalidImageFormatError = "invalid_image_format_error"
    case unauthorizedError = "unauthorized_error"
    case badRequestError = "bad_request_error"
    case resourceNotFoundError = "resource_not_found_error"
    case duplicateDataError = "duplicate_data_error"
    case forbiddenError = "forbidden_error"
    case imageTooLargeErrorTitle = "image_too_large_error_title"
    case imageTooLargeErrorMessage = "image_too_large_error_message"

    // Authentication
    case authenticationPageTitle = "authentication_page_title"
    case authenticationPageSubtitle = "authentication_page_subtitle"
    case firstName = "first_name"
    case lastName = "last_name"
    case email = "email"
    case password = "password"
    case login = "login"
    case logout = "logout"
    case register = "register"
    case registration = "registration"
    case notRegisterYet = "not_register_yet"
    case forgotPassword = "forgot_password"
    case forgotPasswordDescription = "forgot_password_description"
    case registrationStep = "registration_step"
    case selectSchoolLevel = "select_school_level"
    case level = "level"
    case enterNames = "enter_names"
    case enterEmailPassword = "enter_email_password"
    case forgotPasswordSuccess = "forgot_password_success"
    case agreeTermsPrivacyBeginningText = "agree_terms_privacy_beginning_text"
    case termsAndPrivacy = "terms_and_privacy"
    case passwordRegistrationFieldSupportingText = "password_registration_field_supporting_text"
    
    // Authentication errors
    case incorrectEmailFormatError = "incorrect_email_format_error"
    case passwordLengthError = "password_length_error"
    case incorrectCredentialsError = "incorrect_credentials_error"
    case userNotExistError = "user_not_exist_error"
    case emailAlreadyAssociatedError = "email_already_associated_error"
    case legalNoticeNotAcceptedError = "legal_notice_not_aceepted_error"
    case userNotWhiteListedError = "user_not_white_listed_error"
    case authUserNotFoundError = "auth_user_not_found_error"
    
    // News
    case news = "news"
    case announcement = "announcement"
    case recentAnnouncements = "recent_announcements"
    case newAnnouncement = "new_announcement"
    case editAnnouncement = "edit_announcement"
    case title = "title"
    case content = "content"
    case announcementCreated = "announcement_created"
    case noAnnouncement = "no_announcement"
    case deleteAnnouncementAlertMessage = "delete_announcement_alert_message"
    case seeAll = "see_all"
    case allAnnouncements = "all_announcements"
    
    // Message
    case messages = "messages"
    case tapToChat = "tap_to_chat"
    case messagePlaceholder = "message_placeholder"
    case newConversation = "new_conversation"
    case noConversation = "no_conversation"
    case deleteConversationAlertTitle = "delete_conversation_alert_title"
    case deleteConversationAlertMessage = "delete_conversation_alert_message"
    case seen = "seen"
    case newMessage = "new_message"
    case deleteMessageAlertContent = "delete_message_alert_content"
    case chatBlockedUserIndicatorText = "chat_blocked_user_indicator_text"
    case resend = "resend"
    
    // Message error
    case messageFailedToSendError = "message_failed_to_send_error"
    
    // Mission
    case mission = "mission"
    case information = "information"
    case managers = "managers"
    case participants = "participants"
    case tasks = "tasks"
    case newMission = "new_mission"
    case editMission = "edit_mission"
    case participantNumber = "participant_number"
    case shortParticipantNumber = "short_participant_number"
    case noMission = "no_mission"
    case addImage = "add_image"
    case missionDescriptionField = "mission_description_field"
    case missionStartDateField = "mission_start_date_field"
    case missionEndDateField = "mission_end_date_field"
    case missionSchoolLevelField = "mission_school_level_field"
    case everyone = "everyone"
    case missionMaxParticipantsField = "mission_max_participants_field"
    case missionDurationField = "mission_duration_field"
    case addManager = "add_manager"
    case addTask = "add_task"
    case editTask = "edit_task"
    case enterTask = "enter_task"
    case full = "full"
    case noParticipant = "no_participant"
    case seeProfile = "see_profile"
    case completed = "completed"
    
    case registerMissionButtonText = "register_mission_button_text"
    case registeredMissionButtonText = "registered_mission_button_text"
    case completedMissionButtonText = "completed_mission_button_text"
    case registrationClosedMissionButtonText = "registration_closed_mission_button_text"
    case unavailableMissionButtonText = "unavailable_mission_button_text"
    case fullMissionInformationText = "full_mission_information_text"
    case nonMatchingSchoolLevelInformationText = "non_matching_school_level_information_text"
    case completedMissionInformationText = "completed_mission_information_text"
    case deleteMissionAlertMessage = "delete_mission_alert_message"
    case unregisterMissionAlertMessage = "unregister_mission_alert_message"
    case removeParticipantAlertMessage = "remove_participant_alert_message"
    case editMissionSchoolLevelSupportingText = "edit_mission_school_level_supporting_text"
    case selectManagers = "select_managers"
    
    // Mission error
    case maxParticipantsLowerThanCurrentError = "max_participants_lower_than_current_error"
    case maxParticipantNumberReachedError = "max_participant_number_reached_error"
    case schoolLevelNotAllowedError = "school_level_not_allowed_error"
}
